### ISSUE TITLE
Code for multi-view data

### ISSUE THREAD

**Issue by wenbin-lin** [FrozenBurning/Relighting4D#1]
Hi Zhaoxi, 
Thanks for the great work.
It seem that the code and configuration files to handle multi-view data like ZJU Mocap are missing now, will they be released as well?

**Comment by FrozenBurning** [comment]
Hi Wenbin,
Thanks for your interest. The related codes will be released in a few days.

**Comment by FrozenBurning** [comment]
The codes are released, thanks for your patience.
