### ISSUE TITLE
How to get the geometry and reflectance decomposition results.

### ISSUE THREAD

**Issue by 13136983989** [FrozenBurning/Relighting4D#10]
How to get the geometry and reflectance decomposition results on the Blender with self-build BlenderHuman dataset.
![微信截图_20230428170913](https://user-images.githubusercontent.com/42019021/235111778-23df2dca-46ac-418b-86d3-abc78c2b513e.png)

**Comment by FrozenBurning** [comment]
Thanks for your interest in our work. I've uploaded one of the Blender rendering scripts [here](https://drive.google.com/file/d/1WJNdLxbKVPRlKOOnF1NC5C9xyfKBTUVa/view?usp=share_link). Feel free to check it out. Basically, you just need to check different rendering passes to get normal, albedo, and etc.
