### ISSUE TITLE
Why add one to the light source

### ISSUE THREAD

**Issue by Feez2403** [FrozenBurning/Relighting4D#12]
Hello ! Thank you for your amazing work.

I see you are adding torch.ones to the light on the following light if "fix_light" is set to True.

https://github.com/FrozenBurning/Relighting4D/blob/7f69fcfb934571368d45e5cea6e69c2bc062a1a6/lib/networks/relight_microfacet.py#L129

Why is it there and isn't this going to make the new light brighter than it should ?

**Comment by FrozenBurning** [comment]
This is a scene lighting prior in the case that the video you are training on is captured under roughly uniform white lights.
