### ISSUE TITLE
Question about relighting

### ISSUE THREAD

**Issue by Jiatttliu** [FrozenBurning/Relighting4D#16]
Hello！ I want to realize how to get the relighting results like second picture in README.md?(let envmap rotate without the avatar moving)

**Comment by FrozenBurning** [comment]
To relight a static avatar with a rotating envmap as background, you can simply take the first frame (typically any single frame) when relighting a dynamic sequence, which will freeze your avatar to be static. To rotate the background envmap, you can do torch.roll on the tensor of envmap.

**Comment by Jiatttliu** [comment]
Thanks for your reply and advise, I have finished it!
