### ISSUE TITLE
questions about hdr map.

### ISSUE THREAD

**Issue by sunwenzhang1996** [FrozenBurning/Relighting4D#2]
Hi, i downloaded some hdr from poly heaven. But i find some differences between the hdr downloaded and the hdr provided. The max value of the sunset i download is about 30000, but the provide hdr is about 80. Is there any pre-process while dealing with the new hdr map?

**Comment by FrozenBurning** [comment]
The provided HDR is borrowed from [NeRFactor](https://xiuming.info/projects/nerfactor/). Please refer to the google drive link on their project page.

**Comment by sunwenzhang1996** [comment]
alright, thanks!
