### ISSUE TITLE
Missmatch size when Rendering

### ISSUE THREAD

**Issue by dFuong** [FrozenBurning/Relighting4D#3]
I met an trouble when rendering 

![image](https://user-images.githubusercontent.com/48349629/188811726-ef542f28-a922-460a-a4dd-a2d57becf166.png)

Can you support to me?

**Comment by FrozenBurning** [comment]
It's caused by the mismatched version of spconv between the checkpoint and codes. Could you specify the version of spconv you use? I think I've fixed it in a previous commit.

**Comment by dFuong** [comment]
I've checked spconv version in your environment.yml "spconv-cu111" == 2.1.21

**Comment by FrozenBurning** [comment]
Do you use the latest codes? We've fixed it [here](https://github.com/FrozenBurning/Relighting4D/blob/master/lib/utils/net_utils.py#L382).

**Comment by TienDungHUST** [comment]
Hi @FrozenBurning, 
I faced to the same issue. It crash at the `make_network(cfg)`  when it load the 'neuronbody' checkpoint. I think the 'spconv' which you pointed out above is not.  Can you check it again. 
Thank you!
![image](https://user-images.githubusercontent.com/77160942/188834382-d32570ef-7925-4759-b6c0-d34d9444c5eb.png)

**Comment by FrozenBurning** [comment]
@dFuong @TienDungHUST 
Thanks for pointing this out. I've fixed the bug, and have managed to render from our pretrained models on a brand new machine.

**Comment by TienDungHUST** [comment]
@FrozenBurning,
Thank you for supporting. I passed this bug, howerver it raise another problem that I can not download People-snapshot. It seem that dataset link is unavailable. Could you share your own dataset or the dataset's structure with me?
