### ISSUE TITLE
How can I get BlenderHuman synthetic dataset？

### ISSUE THREAD

**Issue by pixiaonuo** [FrozenBurning/Relighting4D#4]

**Comment by FrozenBurning** [comment]
We're not planning to release the BlenderHuman dataset in the near future. If you are urgent to use it, please refer to our [supplementary materials](https://frozenburning.github.io/data/relighting4d_supp.pdf) for details. All modules we used are [Blender](https://www.blender.org/download/) and [SMPL-X Blender add-on](https://gitlab.tuebingen.mpg.de/jtesch/smplx_blender_addon).

**Comment by gushengbo** [comment]
> We're not planning to release the BlenderHuman dataset in the near future. If you are urgent to use it, please refer to our [supplementary materials](https://frozenburning.github.io/data/relighting4d_supp.pdf) for details. All modules we used are [Blender](https://www.blender.org/download/) and [SMPL-X Blender add-on](https://gitlab.tuebingen.mpg.de/jtesch/smplx_blender_addon).

Hello, could you tell me how to get camera intrinsic in blender?
