### ISSUE TITLE
How to get, Normal, Occlusion, Diffuse, Specular informations for self-built dataset

### ISSUE THREAD

**Issue by 13136983989** [FrozenBurning/Relighting4D#5]
We use blender and smpl-x self-built dataset and how to get, Normal, Occlusion, Diffuse, Specular informations.

**Comment by FrozenBurning** [comment]
Please refer to the [rendering process](https://github.com/FrozenBurning/Relighting4D/blob/4ab912f0a25cbc5e12035620a3a091fa4f1d8fbd/lib/networks/renderer/if_clight_renderer.py#L301) during inference.

**Comment by gushengbo** [comment]
> We use blender and smpl-x self-built dataset and how to get, Normal, Occlusion, Diffuse, Specular informations.

hallo, could you tell me whether you use texture map when using blender? Do you only use 2D image in one video when using blender？

**Comment by gushengbo** [comment]
> We use blender and smpl-x self-built dataset and how to get, Normal, Occlusion, Diffuse, Specular informations.

@13136983989 ,Hello, could you tell me If you use blender software, please ask if the smpl parameters and camera parameters are obtained directly from blender or from Easymocap and other models?

**Comment by FrozenBurning** [comment]
@gushengbo Sorry for missing you question so far. For getting necessary 3D assets from Blender, you may refer to this [script](https://drive.google.com/file/d/1WJNdLxbKVPRlKOOnF1NC5C9xyfKBTUVa/view?usp=drive_link).

**Comment by gushengbo** [comment]
> @gushengbo Sorry for missing you question so far. For getting necessary 3D assets from Blender, you may refer to this [script](https://drive.google.com/file/d/1WJNdLxbKVPRlKOOnF1NC5C9xyfKBTUVa/view?usp=drive_link).

Thank you very much. It helps me a lot. Can I ask you three questions? The first one is, I can get the external parameters of the camera from blender, but how do I get the internal parameters of the camera, especially the focal length, what is its unit. Second, Relighting4D needs to get "Rh" and "Th" parameters, how to get them? Third, are the vertices coordinate dimensions I obtained (10475,3) directly usable, or how can they be converted into dimensions of the smpl model?

**Comment by gushengbo** [comment]
> > @gushengbo Sorry for missing you question so far. For getting necessary 3D assets from Blender, you may refer to this [script](https://drive.google.com/file/d/1WJNdLxbKVPRlKOOnF1NC5C9xyfKBTUVa/view?usp=drive_link).
> 
> Thank you very much. It helps me a lot. Can I ask you three questions? The first one is, I can get the external parameters of the camera from blender, but how do I get the internal parameters of the camera, especially the focal length, what is its unit. Second, Relighting4D needs to get "Rh" and "Th" parameters, how to get them? Third, are the vertices coordinate dimensions I obtained (10475,3) directly usable, or how can they be converted into dimensions of the smpl model?

@FrozenBurning excuse me.

**Comment by FrozenBurning** [comment]
I suggest you to take a look of the script I refer to. The camera intrinsic and extrinsic are stored in camera.npz. For "Rh" and "Th" you can refer to the function of `prepare_input` of each dataset respectively. For the third question, the blender script leverages SMPL-X instead of SMPL, you may change the number of latent codes from 6890 to 10475. This is handled in config file (set cfg.smplx = True).

**Comment by gushengbo** [comment]
> I suggest you to take a look of the script I refer to. The camera intrinsic and extrinsic are stored in camera.npz. For "Rh" and "Th" you can refer to the function of `prepare_input` of each dataset respectively. For the third question, the blender script leverages SMPL-X instead of SMPL, you may change the number of latent codes from 6890 to 10475. This is handled in config file (set cfg.smplx = True).

@FrozenBurning  I understand it, thank you very much. I have another question, that is, in the params.py file, I get a 4*4 matrix, can you tell me which is "Rh" and which is "Th" in this matrix?

**Comment by gushengbo** [comment]
> > I suggest you to take a look of the script I refer to. The camera intrinsic and extrinsic are stored in camera.npz. For "Rh" and "Th" you can refer to the function of `prepare_input` of each dataset respectively. For the third question, the blender script leverages SMPL-X instead of SMPL, you may change the number of latent codes from 6890 to 10475. This is handled in config file (set cfg.smplx = True).
> 
> @FrozenBurning I understand it, thank you very much. I have another question, that is, in the params.py file, I get a 4*4 matrix, can you tell me which is "Rh" and which is "Th" in this matrix?

is 'R' the matrix[:3,:3] and "Th" the matrix[:3,3]?

**Comment by FrozenBurning** [comment]
Yes, but it also depends on your coordinate system.

**Comment by FrozenBurning** [comment]
Close due to inactivity. Feel free to reopen for further questions!
