### ISSUE TITLE
bug about your training code

### ISSUE THREAD

**Issue by yjh576** [FrozenBurning/Relighting4D#6]
I directly download your code and run them. However, the process seems to stay at this line

https://github.com/FrozenBurning/Relighting4D/blob/4ab912f0a25cbc5e12035620a3a091fa4f1d8fbd/lib/train/trainers/trainer.py#L41
,and does not continue.
I am confused by this.

**Comment by FrozenBurning** [comment]
Please specify the command you used to launch the training process and the log info from the terminal. It seems that the dataset is not properly set up. For the dataset preparation, please refer to our [README](https://github.com/FrozenBurning/Relighting4D#datasets).
