### ISSUE TITLE
how to relight human with different background

### ISSUE THREAD

**Issue by markgao-916** [FrozenBurning/Relighting4D#7]
Hi Zhaoxi,
Thanks for the great work. I want to konw how to change the background with different HDR image, and the result like your video!
![image](https://user-images.githubusercontent.com/50621508/218977048-2a589ed5-23dc-4971-a29c-ca2671ed9f09.png)

**Comment by FrozenBurning** [comment]
Thanks for your interest in our work! 🍻 
The relighting of the foreground (human body) can be done with our released code. Furthermore, you can use the alpha map as a mask to blend foreground and background together. And the background image is rendered by a perspective camera which projects the HDR panorama back to the camera view. Here is a [toolbox](https://github.com/NitishMutha/equirectangular-toolbox) for your reference.

**Comment by markgao-916** [comment]
Thanks for your reply, i will try.

**Comment by FrozenBurning** [comment]
Closed due to inactivity. Feel free to reopen it if you have any issues.
