### ISSUE TITLE
Different light settings between people-snapshot and zju-mocap 

### ISSUE THREAD

**Issue by sypj-98** [FrozenBurning/Relighting4D#8]
Hi Zhaoxi,
Thanks for your great work!
It seems like zju-mocap and people-snapshot use different light settings. I'm confused about that, could you please explain that?
```       
if 'xyzc' in cfg.exp_name or 'zju' in cfg.exp_name:
            print("zju-mocap:{}, using different lighting......".format(cfg.exp_name))
            lxyz[...,1] = -lxyz[...,1]
            lxyz[...,0] = -lxyz[...,0]
        else:
            lxyz = lxyz[..., [0, 2, 1]]
            lxyz[...,1] = -lxyz[...,1]
```
If I wanna train the model on my own dataset, which one should I choose?
Thanks in advance!

**Comment by FrozenBurning** [comment]
Thanks for your interest in our work! It's caused by different definitions of the world coordinate system in different datasets. If you wanna train on your own dataset, please align your coordinate system to either People-Snapshot or ZJU-Mocap, and choose the corresponding light setting.

**Comment by sypj-98** [comment]
Thanks for your reply, it helps me a lot!
