### ISSUE TITLE
Have some questions about trian and inference in monocular video

### ISSUE THREAD

**Issue by gushengbo** [FrozenBurning/Relighting4D#9]
Hello, happy for your good job. I have a question if only training in single view video, the camera pose ωo is fixed. Therefore, I can only relight human in one camera pose ωo.

**Comment by FrozenBurning** [comment]
Thanks for your interest in our work! I'm a little bit confused about your question. Relighting in novel views typically has two different ways, rotating SMPL vertices of the human or moving the camera. We choose the former one.

**Comment by gushengbo** [comment]
> Thanks for your interest in our work! I'm a little bit confused about your question. Relighting in novel views typically has two different ways, rotating SMPL vertices of the human or moving the camera. We choose the former one.

Thank you. I get it. This means that if I train with only one video, ray_o is fixed and I can't move camera when relighting in novel views.

**Comment by FrozenBurning** [comment]
Closed. Feel free to reopen it if your have any question 🍻
